CREATE DATABASE IF NOT EXISTS scis;

ALTER DATABASE scis
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON scis.* TO pc@localhost IDENTIFIED BY 'pc';

USE scis;

CREATE TABLE IF NOT EXISTS sct (
  id INT(4) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  no VARCHAR(30),
  name VARCHAR(30),
  depart VARCHAR(30),
  course VARCHAR(30),
  grade INT(4)
) engine=InnoDB;

